@host=https://localhost:7074

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Eric",
    "lastName": "Aldrich",
    "email": "lanndrich@gmail.com",
    "password": "lolokay"
}