@host=https://localhost:7074

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlYWNjNTM0Ni1mNmQwLTRlZTgtOWJkZC1lODk0OThkY2RjY2YiLCJnaXZlbl9uYW1lIjoiRXJpYyIsImZhbWlseV9uYW1lIjoiQWxkcmljaCIsImp0aSI6ImVlOGIwOWEwLTY2YjItNDI5Ni1hNWM0LWFlM2I2MTc5ZjUxMyIsImV4cCI6MTY3MTQ3NDA1OSwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.oNgaIOLPZYsQvaubNLOQcjTjVEN0fR57VPCRG0npN7M