@host=https://localhost:7074

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4OTE2MTMxZi02ZDcxLTQyNjQtYTY5Ni1mN2EzN2I1NTBlMjUiLCJnaXZlbl9uYW1lIjoiRXJpYyIsImZhbWlseV9uYW1lIjoiQWxkcmljaCIsImp0aSI6IjZhMGJjN2UwLWQwNjQtNDc0MC05OTc0LWM2NzEzMzgxYjk4ZCIsImV4cCI6MTY3MTI0Mjc2NiwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.E4EKiqNvyFJQxcJsl7Swat8E_TFuSf8w1Aus1GsRvRU